
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public E getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 *
 * @author Zach Bryant
 * @author Guillermo Macbeath
 * @author Monilito Castro
 */
public class homescreen extends javax.swing.JPanel {

    /**
     * Creates new form homescreen
     */
    private Color backcolor;
    private Project project;
    private DefaultListModel listModel1 = new DefaultListModel();
    private DefaultListModel listModel2  = new DefaultListModel();
    private DefaultTableModel table;
    public homescreen( Project p ) {
        initComponents();
        project = p;
        backcolor = jComboBox2.getBackground();
        table = (DefaultTableModel) jTable1.getModel();
        
        listModel2.addElement("CSC 101");
        listModel2.addElement("CSC 201");
        listModel2.addElement("CSC 301");
        listModel2.addElement("ANTH 101");
        listModel2.addElement("ANTH 201");
        listModel2.addElement("ANTH 301");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Transcript = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Planner = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jCourseDesc = new javax.swing.JTextArea();
        Enroll = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        FinancialAid = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        balance = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 200));

        Transcript.setForeground(new java.awt.Color(0, 0, 200));

        jButton3.setText("View Unnofficial ");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Order Official");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TranscriptLayout = new javax.swing.GroupLayout(Transcript);
        Transcript.setLayout(TranscriptLayout);
        TranscriptLayout.setHorizontalGroup(
            TranscriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TranscriptLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton3)
                .addGap(56, 56, 56)
                .addComponent(jButton4)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        TranscriptLayout.setVerticalGroup(
            TranscriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TranscriptLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(TranscriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transcript", Transcript);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Deparment", "Anthropology", "Computer Science" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Department:");

        jLabel5.setText("Courses:");

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Remove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Course Description:");

        jList1.setModel(listModel1);
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Cart");

        jCourseDesc.setColumns(20);
        jCourseDesc.setLineWrap(true);
        jCourseDesc.setRows(5);
        jCourseDesc.setText("Please Select a Course from\nthe menu.");
        jScrollPane4.setViewportView(jCourseDesc);

        javax.swing.GroupLayout PlannerLayout = new javax.swing.GroupLayout(Planner);
        Planner.setLayout(PlannerLayout);
        PlannerLayout.setHorizontalGroup(
            PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlannerLayout.createSequentialGroup()
                        .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PlannerLayout.createSequentialGroup()
                                .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton6)
                                    .addComponent(jLabel4))
                                .addGap(144, 144, 144))
                            .addComponent(jScrollPane4))
                        .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PlannerLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PlannerLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PlannerLayout.setVerticalGroup(
            PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlannerLayout.createSequentialGroup()
                .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PlannerLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlannerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planner", Planner);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8 AM", null, null, null, null, null},
                {"9", null, null, null, null, null},
                {"10", "CSC 201", null, "CSC 201", null, "CSC 201"},
                {"11", null, "ANTH 101", null, "ANTH 101", null},
                {"12 PM", null, "CSC 101", null, "CSC 101", null},
                {"1", "ANTH 201", null, "ANTH 201", null, "ANTH 201"},
                {"2", null, "ANTH 301", null, "ANTH 301", null},
                {"3", "CSC 301", null, "CSC 301", null, "CSC 301"},
                {"4", null, null, null, null, null},
                {"5", null, null, null, null, null},
                {"6", null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thusday", "Friday"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jList4.setModel(listModel2);
        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(jList4);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnrollLayout = new javax.swing.GroupLayout(Enroll);
        Enroll.setLayout(EnrollLayout);
        EnrollLayout.setHorizontalGroup(
            EnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnrollLayout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(EnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton7)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        EnrollLayout.setVerticalGroup(
            EnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(58, 58, 58)
                .addComponent(jButton7)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("Enroll", Enroll);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Aid Year", "2013-2014", "2014-2015" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Aid Type", "Availabel Amount", "Accepted Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(25);
        jScrollPane5.setViewportView(jTable3);

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Accept");

        jLabel2.setText("Decline");

        buttonGroup1.add(jRadioButton5);

        buttonGroup2.add(jRadioButton6);

        buttonGroup3.add(jRadioButton7);

        buttonGroup4.add(jRadioButton8);

        buttonGroup1.add(jRadioButton9);

        buttonGroup2.add(jRadioButton10);

        buttonGroup3.add(jRadioButton11);

        buttonGroup4.add(jRadioButton12);

        javax.swing.GroupLayout FinancialAidLayout = new javax.swing.GroupLayout(FinancialAid);
        FinancialAid.setLayout(FinancialAidLayout);
        FinancialAidLayout.setHorizontalGroup(
            FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinancialAidLayout.createSequentialGroup()
                .addGap(0, 331, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(39, 39, 39))
            .addGroup(FinancialAidLayout.createSequentialGroup()
                .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinancialAidLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinancialAidLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FinancialAidLayout.setVerticalGroup(
            FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancialAidLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinancialAidLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FinancialAidLayout.createSequentialGroup()
                                .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FinancialAidLayout.createSequentialGroup()
                                        .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(FinancialAidLayout.createSequentialGroup()
                                                .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton5))
                                            .addComponent(jRadioButton9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton6))
                                    .addComponent(jRadioButton10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton7))
                            .addComponent(jRadioButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton12)))
                    .addGroup(FinancialAidLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(FinancialAidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(148, 148, 148))
        );

        jTabbedPane1.addTab("Financial Aid", FinancialAid);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane7.setViewportView(jTextArea1);
        jTextArea1.setVisible(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semester", "Fall 2012", "Fall 2013", "Spring 2012", "Spring 2014" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balanceLayout = new javax.swing.GroupLayout(balance);
        balance.setLayout(balanceLayout);
        balanceLayout.setHorizontalGroup(
            balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceLayout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        balanceLayout.setVerticalGroup(
            balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Balance", balance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //displays text file in text field
        project.generateGui("unofficial");
        project.jButton3.setVisible(true);
        FileReader fr;
        try {
            fr = new FileReader("unofficial.txt");
            project.order.jTextArea2.read(fr, "unofficial.txt");
            fr.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
        }     
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[] rem = new int[10];
        rem=jList1.getSelectedIndices();
        int n = rem.length;
        for (int i=n-1;i>=0;i--)
            listModel1.removeElementAt(rem[i]);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       //order transcript screen 1
        project.generateGui("order1");
        project.jButton3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // sets components according to department selection
        String msg = (String)evt.getItem();
        DefaultListModel listModel = new DefaultListModel();

        
        switch(msg){
            case "Anthropology":
                listModel.addElement("Anth 101");
                listModel.addElement("Anth 201");
                listModel.addElement("Anth 301");
                jList2.setModel(listModel);
                break;
            case "Computer Science":
                listModel.addElement("CSC 101");
                listModel.addElement("CSC 201");
                listModel.addElement("CSC 301");
                jList2.setModel(listModel);
                break;
            default:
                listModel.addElement("");
                jList2.setModel(listModel);
                break;
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // sets description according to selection of course
        //String msg =  evt.
        String msg = jList2.getSelectedValue().toString();
        String x = "";
        
        switch(msg){
            case "CSC 101":
                x = "CSC 101 \n\nComputer Science 1\n Required for Computer Science Majors and Minors. Will program in Python learning FOR, DO, and WHILE loops. Nested and iterative algorithms are explored.";
                break;
            case "CSC 201":
                x="CSC 201 \n\nUser Interface Development\n Students explore GUI programming using SWING. Will need to create a team and present a GUI like their life depended on it.";
                break;
            case "CSC 301":
                x="CSC 301\n\nSystems Programming\nStudents explore programing with C to create system programs.";
                break;
            case "Anth 101":
                x="Anth 101\n\nAnthropology 1\nRequirement for Anthropology Majors. Will explore anthropological methods to study cultures. Student learns the history and accounts of anthropologists";
                break;
            case "Anth 201":
                x="Anth 201\n\nEthnographing Methodology\nStudents learn ethnographing methods such as survey, communication, and culture studies.";
                break;
            case "Anth 301":
                x="Anth 301\n\nApplication of Anthropology\nStudents learn how ethnographic methods are applied to real-world situations. Topics involve are application in marketing, and social negotiation.";
                break;
        }
        jCourseDesc.setText(x);
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //adds elements from all courses to users selected courses
        String element = jList2.getSelectedValue().toString();
        if(listModel1.contains(element)==false)
            listModel1.addElement(element);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    double selected;
    double available;
    TableModel tab = jTable3.getModel();
    
    //if accepted then it checks if selected amount is over available amount if so it sets accepted to available amount
    if(jRadioButton5.isSelected()){
        try{
            selected = (double) tab.getValueAt(0, 2);
            available = (double) tab.getValueAt(0, 1);
            System.out.println(selected);
            if(selected >= available)
                tab.setValueAt(available, 0, 2);
            else
                tab.setValueAt(selected, 0, 2);
        }
        catch(NullPointerException e)
        {
            tab.setValueAt(0,0,2);
        }
        
    }
    if(jRadioButton6.isSelected()){
        try{
            selected = (double) tab.getValueAt(1, 2);
            available = (double) tab.getValueAt(1, 1);
            System.out.println(selected);
            if(selected >= available)
                tab.setValueAt(available, 1, 2);
            else
                tab.setValueAt(selected, 1, 2);
        }
        catch(NullPointerException e)
        {
            tab.setValueAt(0,1,2);
        }
    }
    if(jRadioButton7.isSelected()){
        try{
            selected = (double) tab.getValueAt(2, 2);
            available = (double) tab.getValueAt(2, 1);
            System.out.println(selected);
            if(selected >= available)
                tab.setValueAt(available, 2, 2);
            else
                tab.setValueAt(selected, 2, 2);
        }
        catch(NullPointerException e)
        {
            tab.setValueAt(0,2,2);
        }
    }
    if(jRadioButton8.isSelected()){
        try{
            selected = (double) tab.getValueAt(3, 2);
            available = (double) tab.getValueAt(3, 1);
            System.out.println(selected);
            if(selected >= available)
                tab.setValueAt(available, 3, 2);
            else
                tab.setValueAt(selected, 3, 2);
        }
        catch(NullPointerException e)
        {
            tab.setValueAt(0,3,2);
        }
    }
    //sets accepted amount to zero if declined
    if(jRadioButton9.isSelected())
        tab.setValueAt(0, 0, 2);
    if(jRadioButton10.isSelected())
        tab.setValueAt(0, 1, 2);
    if(jRadioButton11.isSelected())
        tab.setValueAt(0, 2, 2);
    if(jRadioButton12.isSelected())
        tab.setValueAt(0, 3, 2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        TableModel tab = jTable3.getModel();
        //sets financial aid data for selected years
        if(jComboBox1.getSelectedIndex()==0){        
            tab.setValueAt(null, 0, 0);
            tab.setValueAt(null, 0, 1);
            tab.setValueAt(null, 0, 2);
            tab.setValueAt(null, 1, 0);
            tab.setValueAt(null, 1, 1);
            tab.setValueAt(null, 1, 2);
            tab.setValueAt(null, 2, 0);
            tab.setValueAt(null, 2, 1);
            tab.setValueAt(null, 2, 2);
            tab.setValueAt(null, 3, 0);
            tab.setValueAt(null, 3, 1);
            tab.setValueAt(null, 3, 2);
        }
        else if(jComboBox1.getSelectedIndex()==1){        
            tab.setValueAt("Sub Federal Loan", 0, 0);
            tab.setValueAt( 2000.0, 0, 1);
            tab.setValueAt(null, 0, 2);
            tab.setValueAt("Unsub Federal Loan", 1, 0);
            tab.setValueAt( 7000.0, 1, 1);
            tab.setValueAt(null, 1, 2);
            tab.setValueAt("Private Loan", 2, 0);
            tab.setValueAt( 10000.0, 2, 1);
            tab.setValueAt(null, 2, 2);
            tab.setValueAt("UND Scholarship", 3, 0);
            tab.setValueAt( 3000.0, 3, 1);
            tab.setValueAt(null, 3, 2);
        }
        else if(jComboBox1.getSelectedIndex()==2){        
            tab.setValueAt("Sub Federal Loan", 0, 0);
            tab.setValueAt( 4000.0, 0, 1);
            tab.setValueAt(null, 0, 2);
            tab.setValueAt("Unsub Federal Loan", 1, 0);
            tab.setValueAt( 6000.0, 1, 1);
            tab.setValueAt(null, 1, 2);
            tab.setValueAt("Private Loan", 2, 0);
            tab.setValueAt( 12000.0, 2, 1);
            tab.setValueAt(null, 2, 2);
            tab.setValueAt("UND Scholarship", 3, 0);
            tab.setValueAt( 4000.0, 3, 1);
            tab.setValueAt(null, 3, 2);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //resets accepted amounts to zero and sends back to main tab
        TableModel tab = jTable3.getModel();
        tab.setValueAt(null, 0, 2);
        tab.setValueAt(null, 1, 2);
        tab.setValueAt(null, 2, 2);
        tab.setValueAt(null, 3, 2);       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jComboBox2.getSelectedIndex()==0){
           jComboBox2.setBackground(Color.red);
           jTextArea1.setText(null);
           jTextArea1.setVisible(false);}
        else if(jComboBox2.getSelectedIndex()==1){
            jTextArea1.setVisible(true);
            FileReader fr;
            try {
                fr = new FileReader("Fall 2012.txt");
                jTextArea1.read(fr, "Fall 2012.txt");
                fr.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
        else if(jComboBox2.getSelectedIndex()==2){
            jTextArea1.setVisible(true);
            FileReader fr;
            try {
                fr = new FileReader("Fall 2013.txt");
                jTextArea1.read(fr, "Fall 2013.txt");
                fr.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        else if(jComboBox2.getSelectedIndex()==3){
           jTextArea1.setVisible(true);
           FileReader fr;
           try {
               fr = new FileReader("Spring 2013.txt");
               jTextArea1.read(fr, "Spring 2013.txt");
               fr.close();
           } catch (FileNotFoundException ex) {
               Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IOException ex) {
               Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
           } 
        }
        else if(jComboBox2.getSelectedIndex()==4){
           jTextArea1.setVisible(true);
           FileReader fr;
           try {
               fr = new FileReader("Spring 2014.txt");
               jTextArea1.read(fr, "Spring 2014.txt");
               fr.close();
           } catch (FileNotFoundException ex) {
               Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IOException ex) {
               Logger.getLogger(homescreen.class.getName()).log(Level.SEVERE, null, ex);
           } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
       jComboBox2.setBackground(backcolor);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String text = "";
        String text2 = "";
        
        int[] rem = new int[10];
        rem=jList4.getSelectedIndices();
        int n = rem.length;
        for (int i=n-1;i>=0;i--){
            text =listModel2.getElementAt(rem[i]).toString();
            listModel2.removeElementAt(rem[i]);
        }
        
        for (int j = 0; j < 8; j++){
            for (int k = 0; k < 6; k++){

                try {
                    if (!(table.getValueAt(j, k).equals(null))){
                        text2 = table.getValueAt(j, k).toString();
                        if (text2 == text)
                            table.setValueAt("", j, k);
                    }
                }
                catch (NullPointerException e) {}
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Enroll;
    private javax.swing.JPanel FinancialAid;
    private javax.swing.JPanel Planner;
    private javax.swing.JPanel Transcript;
    public javax.swing.JPanel balance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JTextArea jCourseDesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList4;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable3;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
