
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach Bryant
 * @author Guillermo Macbeath
 * @author Monilito Castro
 */
public class mainMenu extends javax.swing.JPanel {

    /**
     * Creates new form mainMenu
     */
    private Project project;
    private CardLayout cl;
    public mainMenu( Project p ) {
        initComponents();
        project = p;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbLogin1 = new javax.swing.JLabel();
        txtUser1 = new javax.swing.JTextField();
        pfPassword1 = new javax.swing.JPasswordField();
        btnAccept1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Khmer UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 0));
        jLabel2.setText("UND");

        lbLogin1.setText("Student Login");

        pfPassword1.setText("jPasswordField1");
        pfPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPassword1FocusGained(evt);
            }
        });
        pfPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPassword1KeyPressed(evt);
            }
        });

        btnAccept1.setLabel("Accept");
        btnAccept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccept1ActionPerformed(evt);
            }
        });

        btnCancel1.setLabel("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Claim Account");
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField1.setEnabled(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("Forgot Password?");
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 51, 255));
        jTextField3.setEnabled(false);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbLogin1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAccept1)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancel1))
                                .addComponent(pfPassword1)
                                .addComponent(txtUser1))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(lbLogin1)
                .addGap(18, 18, 18)
                .addComponent(txtUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept1)
                    .addComponent(btnCancel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccept1ActionPerformed
    login();

    }//GEN-LAST:event_btnAccept1ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // close program
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void pfPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassword1FocusGained
        // TODO add your handling code here:
        pfPassword1.setText("");
    }//GEN-LAST:event_pfPassword1FocusGained

    private void pfPassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassword1KeyPressed
        char c=evt.getKeyChar();
        if(c==KeyEvent.VK_ENTER)
            login();
    }//GEN-LAST:event_pfPassword1KeyPressed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        project.generateGui("claim");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        project.generateGui("forgot");
    }//GEN-LAST:event_jTextField3MouseClicked

    private void login()
    {
        //used to check for admin login
        if(txtUser1.getText().matches("admin"))
        {
            if(pfPassword1.getText().matches("admin"))
            {
                //run program in admin mode
                lbLogin1.setText("Student Login");
                lbLogin1.setForeground(Color.black);
                project.generateGui("select");
            }
            else
            {
                //incorrect password
                lbLogin1.setText("Incorrect Password");
                lbLogin1.setForeground(Color.red);
            }
        }
        //used to check for student login
        else if (txtUser1.getText().matches("user1"))
        {
            if(pfPassword1.getText().matches("user1"))
            {
                //run program in user mode
                lbLogin1.setText("Student Login");
                lbLogin1.setForeground(Color.black);
                project.jPanel1.setVisible(true);
                project.jButton4.setVisible(true);
                project.jLabel2.setText("You are logged in as: User1");
                project.generateGui("home",12);
            }
    
            else
            {
                //incorrect password
                lbLogin1.setText("Incorrect Password");
                lbLogin1.setForeground(Color.red);
            }
        }
        //login doesn't match any current data on file
        else
        {
            //user name doesn't match
            lbLogin1.setText("Incorrect Username");
            lbLogin1.setForeground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept1;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbLogin1;
    public javax.swing.JPasswordField pfPassword1;
    public javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables
}
